### ISSUE TITLE
Julia codes - python library changes

### ISSUE THREAD

**Issue by sebkaz** [ftheberge/GraphMiningNotebooks#4]
Hi. 
In all Julia notebooks, we need to change the python sklearn library name 

for example in notebook5 : 
**we have**
run(`$(PyCall.python) -m pip install sklearn`)
**it should be**
run(`$(PyCall.python) -m pip install scikit-learn`)

The reason why code is run and we don't see errors is that at PyPi there exists a sklearn library but it is not a correct package.

**Comment by bkamins** [comment]
Fixed. thank you!
